### PR TITLE
Disable deleting a deployment configuration

### PR DESCRIPTION
**Pull request by luanecavalcantizup**
### Screenshot (after):
image

### CODE REVIEW

**Review by leandrorodrigueszup — CHANGES_REQUESTED** [review]
I have not seen were you verify if there is any active deployment.

**Comment by luanecavalcantizup** [comment]
will be done in a hotfix

**Comment by luanecavalcantizup** [comment]
It will be resumed.

**Comment by luanecavalcantizup** [comment]
close this pr because it needs more verification that is already been doing in a task

**Pull request closed without merging**
